version: '3.4'

services:
    
    frontend: 
        image: ${REPOSITORY_URI}-fe:$BUILD_NUMBER
        build:
            context: ClassifiedsBlazor
            dockerfile: Dockerfile
        environment:
            - BackendUrl=http://backend
        ports: 
            - "5299:80"
        depends_on:
            - backend       
    backend:
        image: ${REPOSITORY_URI}-be:$BUILD_NUMBER
        build:
            context: cb.api
            dockerfile: Dockerfile
        ports: 
            - "5012:80"
