version: '3.4'

services:
    
    frontend: 
        image: ${REPOSITORY_URI}:fe
        build:
            context: ClassifiedsBlazor
            dockerfile: Dockerfile
        environment:
            - BackendUrl=http://backend
        ports: 
            - "5299:80"
        depends_on:
            - backend       
    backend:
        image: ${REPOSITORY_URI}:be
        build:
            context: cb.api
            dockerfile: Dockerfile
        ports: 
            - "5012:80"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - USER_SECRETS_ID=c09811bb-8a45-4a0f-8a56-10c53b08f6e6
        volumes:
            - $APPDATA/Microsoft/UserSecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID
            - $HOME/.microsoft/usersecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID

